import Head from "next/head";
// import Image from "next/image";
import { useCallback, useState } from "react";
import Leg from "../components/Leg";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [legs, setLegs] = useState([{ value: 1 }, { value: 1 }]);

  const updateLegs = useCallback(
    (index: number, value: number) => {
      const newLegs = [...legs];
      newLegs[index].value = value;
      setLegs(newLegs);
    },
    [legs]
  );

  const addLeg = useCallback(() => {
    setLegs([...legs, { value: 1 }]);
  }, [legs]);

  const deleteLeg = useCallback(
    (index: number) => {
      const newLegs = [...legs];
      newLegs.splice(index, 1);
      setLegs(newLegs);
    },
    [legs]
  );

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen w-screen">
        <div className="flex items-center">
          <div className="w-1/2 space-y-4">
            <button className="bg-blue-400 text-white" onClick={() => addLeg()}>
              Add Leg
            </button>

            {legs.map((leg: { value: any }, index: any) => (
              <Leg
                key={index}
                lot={leg.value}
                onLotChange={(value: number) => updateLegs(index, value)}
                onCopy={() => setLegs(() => [...legs, { value: leg.value }])}
                onDelete={() => deleteLeg(index)}
              />
            ))}
          </div>
          <div className="bg-gray-800 w-1/2">
            {legs.map((leg: { value: any }, index: any) => (
              <div key={index}>
                <p className="text-white">
                  {index} : <strong>{leg.value}</strong>
                </p>
              </div>
            ))}
          </div>
        </div>
      </main>
    </div>
  );
}
